### ISSUE TITLE
I suggest using a listener or visitor -listener or -visitor option on ANTLR

### ISSUE THREAD

**Issue by parrt** [jsrosman/kata_pct#1]
hi Johan!! It looks pretty good to me though nowadays I suggest that people let the parser built a parse tree automatically and then use a listener to do the actions you have there. For each rule or labeled alternative in the grammar there is an equivalent enter and exit method in the listener that you can override to perform your operations. You might try that to see if it looks cleaner. In that way, the grammar is not tied to a specific language or even the same application.

**Comment by jsrosman** [comment]
Indeed it was a surprise to discover tree listeners in new ANTLR version. (See Chapter 7 of Ter's ANTLR v4 book). I added try2  with the tree listener implementation.
